# inherit_from:
#   - ../.rubocop.yml

#require:
#  - rubocop-performance

AllCops:
  #TargetRubyVersion: 3.2
  #NewCops: enable
  Exclude: []

Style/SymbolArray:
  EnforcedStyle: percent

Style/WordArray:
  EnforcedStyle: percent

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
  EnforcedShorthandSyntax: either

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/RedundantReturn:
  AllowMultipleReturnValues: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericLiterals:
  MinDigits: 7

Style/CommandLiteral:
  EnforcedStyle: percent_x

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    "%x": "[]"

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Layout/LineLength:
  Enabled: true
  Max: 200
  Exclude: []

Layout/HashAlignment:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Layout/LeadingCommentSpace:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: space

Metrics/MethodLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']
  Max: 100
  Exclude: []

Metrics/BlockLength:
  Enabled: true
  CountAsOne: ['array', 'heredoc', 'method_call']
  Max: 100
  Exclude: []

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Lint/RescueException:
  Enabled: false
