# This is the release workflow that builds an asset and creates a release whenever a v* tag is created

name: Create Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build tar.gz
        run: tar zcf gpgrelay.tar.gz relay.rb gpg_relay_wsl.rb gpg_relay_win.rb Gemfile Gemfile.lock README.md ReleaseNotes.md systemd

      - name: Build zip
        run: zip gpgrelay.zip relay.rb gpg_relay_wsl.rb gpg_relay_win.rb Gemfile Gemfile.lock README.md ReleaseNotes.md systemd

      - name: Release
        id: create_release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ github.ref }}
          body_path: ReleaseNotes.md
          draft: false
          prerelease: ${{ contains(github.ref, '-pre') }}
          files: |-
            gpgbridge.tar.gz
            gpgbridge.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
